Repository COS301-SE-2022/Japanese-Writing-Evaluator, pull requests merged in 2022-05, with the labels that each got.

#9 🔥 (Frontend feature authentication) Changing from React to Angular
  .eslintrc.json
  .github/workflows/frontendTest.yml
  .github/workflows/metaData.yml
  .gitignore
  .prettierrc.json
  .vscode/settings.json
  capacitor.config.ts
  ionic.config.json
  package.json
  public/assets/icon/favicon.png
  public/assets/icon/icon.png
  public/assets/shapes.svg
  public/index.html
  public/manifest.json
  src/App.test.tsx
  src/App.tsx
  src/components/ExploreContainer.css
  src/components/ExploreContainer.tsx
  src/index.tsx
  src/pages/Tab1.css
  src/pages/Tab1.tsx
  src/pages/Tab2.css
  src/pages/Tab2.tsx
  src/pages/Tab3.css
  src/pages/Tab3.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  src/setupTests.ts
  src/theme/variables.css
  tsconfig.json
  yarn.lock
Labels: scope:frontend

#21 ✨ (frontend -feature-authentication) added images
  README.md
Labels: enhancement, scope:frontend

#24 ✨(Forgot Password) added forgot password functions
  .gitignore
  api/__pycache__/app.cpython-38.pyc
  api/__pycache__/app.cpython-39.pyc
  api/app.py
  api/database.py
  backend/api/__pycache__/app.cpython-38.pyc
  backend/api/__pycache__/app.cpython-39.pyc
  backend/api/__pycache__/database.cpython-38.pyc
  backend/api/__pycache__/database.cpython-39.pyc
  backend/api/__pycache__/main.cpython-38.pyc
  backend/api/app.py
  backend/database/__pycache__/database.cpython-38.pyc
  backend/database/__pycache__/database.cpython-39.pyc
  backend/database/database.py
  backend/sendEmail.py
  package.json
Labels: scope:backend, layer:api, layer:service

#23 📦 (main) Update develop branch
  .gitignore
  api/__pycache__/app.cpython-38.pyc
  api/app.py
  api/database.py
  backend/api/__pycache__/app.cpython-38.pyc
  backend/api/__pycache__/app.cpython-39.pyc
  backend/api/__pycache__/database.cpython-38.pyc
  backend/api/__pycache__/database.cpython-39.pyc
  backend/api/__pycache__/main.cpython-38.pyc
  backend/api/app.py
  backend/database/__pycache__/database.cpython-38.pyc
  backend/database/__pycache__/database.cpython-39.pyc
  backend/database/database.py
  backend/sendEmail.py
  package.json
Labels: scope:frontend

#31 Revert "Merging"
  api/Storage/firebaseConfig.ts
  yarn.lock
Labels: invalid, scope:backend, layer:api

#32 ✨(Backend feature upload image) Added api and service for upload image
  backend/Storage/firebaseConfig.ts
  backend/api/app.py
  backend/database/__pycache__/database.cpython-39.pyc
  backend/database/database.py
  backend/test/unittest/uploadImage_test.py
Labels: scope:backend, layer:api, layer:service

#27 ✨ (Frontend-feature-authentication) Setup Forget Password Page
  package-lock.json
  src/app/app-routing.module.ts
  src/app/forgot-password/forgot-password-routing.module.ts
  src/app/forgot-password/forgot-password.module.ts
  src/app/forgot-password/forgot-password.page.html
  src/app/forgot-password/forgot-password.page.scss
  src/app/forgot-password/forgot-password.page.spec.ts
  src/app/forgot-password/forgot-password.page.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/sign-up/sign-up-routing.module.ts
  src/app/sign-up/sign-up.module.ts
  src/app/sign-up/sign-up.page.html
  src/app/sign-up/sign-up.page.scss
  src/app/sign-up/sign-up.page.spec.ts
  src/app/sign-up/sign-up.page.ts
  src/assets/Logo.png
  src/assets/backgroundTop.jpeg
  src/theme/variables.scss
  yarn.lock
Labels: enhancement, scope:frontend

#19 ⚡️Backend feature database user functions- Add email to findUser
  backend/api/app.py
  backend/database/__pycache__/database.cpython-310.pyc
  backend/database/database.py
Labels: scope:database, layer:service

#38 Backend feature view image
  backend/api/app.py
  backend/database/database.py
Labels: scope:backend, layer:api, layer:service

#40 ✨ (Frontend-feature-authentication) Setup forgot password and sign in page
  src/app/forgot-password/forgot-password.page.html
  src/app/forgot-password/forgot-password.page.scss
  src/app/forgot-password/forgot-password.page.spec.ts
  src/app/login/login.page.html
  src/app/login/login.page.spec.ts
  src/app/sign-up/sign-up.page.html
  src/app/sign-up/sign-up.page.scss
  src/app/sign-up/sign-up.page.spec.ts
  src/app/sign-up/sign-up.page.ts
Labels: enhancement, scope:frontend

#41 🔒(Backend feature authentication) Added JWT Tokens
  backend/api/app.py
  backend/api/requirements.txt
  backend/database/database.py
Labels: scope:backend, layer:api

#44 ✨(Frontend feature authentication) connected frontend to backend
  backend/api/app.py
  backend/database/__pycache__/database.cpython-39.pyc
  package.json
  src/app/app.module.ts
  src/app/home/home.page.html
  src/app/login/login.page.html
  src/app/login/login.page.spec.ts
  src/app/login/login.page.ts
  src/app/rest.service.spec.ts
  src/app/rest.service.ts
  src/app/services/app-service.service.ts
  src/app/sign-up/sign-up.module.ts
  src/app/sign-up/sign-up.page.html
  src/app/sign-up/sign-up.page.spec.ts
  src/app/sign-up/sign-up.page.ts
  src/app/sign-up/sign-up.ts
Labels: scope:frontend

#43 ✨ (frontend-feature-SuggestCharacters)
  Storage/firebaseConfig.ts
  src/app/home/home.page.html
  src/app/home/home.page.scss
  src/app/home/home.page.ts
Labels: scope:frontend

#35 ✅ (backend-feature--SuggestCharacters) add tests
  backend/api/app.py
  backend/test/unittest/test_register.py
Labels: scope:backend, layer:api

#46 :sparkles: (Frontend feature upload image) Added the upload image feature
  Storage/firebaseConfig.ts
  package.json
  src/app/app.module.ts
  src/app/home/home.module.ts
  src/app/home/home.page.html
  src/app/home/home.page.scss
  src/app/home/home.page.spec.ts
  src/app/home/home.page.ts
  src/app/login/login.page.html
  src/app/services/app-service.service.ts
  src/app/sign-up/sign-up.page.spec.ts
  yarn.lock
Labels: scope:frontend

#48 :bug: (Frontend feature upload image) add html
  src/app/home/home.page.html
Labels: scope:frontend

#50 :white_check_mark: (Frontend-feature-upload) added tests
  backend/api/app.py
  backend/database/__pycache__/database.cpython-310.pyc
  src/app/home/home.page.html
  src/app/home/home.page.scss
  src/app/home/home.page.spec.ts
  src/app/home/home.page.ts
  src/app/login/login.page.ts
  src/app/services/app-service.service.ts
Labels: scope:frontend

#49 🐛 (Backend-feature--suggest characters) Fixed a bug in register unit test
  backend/database/database.py
  backend/test/unittest/test_register.py
  src/app/home/home.page.html
Labels: scope:backend, scope:database

#51 Develop
  backend/api/app.py
  backend/database/__pycache__/database.cpython-310.pyc
  backend/database/database.py
  backend/test/unittest/test_register.py
  src/app/home/home.page.html
  src/app/home/home.page.scss
  src/app/home/home.page.ts
  src/app/login/login.page.ts
  src/app/services/app-service.service.ts
Labels: scope:frontend

#52 ✨ (Frontend-feature-authentication) Progress page implemented
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/progress/progress.page.html
  src/app/progress/progress.page.spec.ts
  src/app/progress/progress.page.ts
Labels: scope:frontend

#54 👍 (frontend-feature-authentication)fixxed html
  src/app/progress/progress.page.html
Labels: scope:frontend

#47 ✅ (frontend-feature-SuggestCharacters)add test for suggest character
  src/app/home/home.page.spec.ts
  src/app/home/home.page.ts
Labels: scope:frontend

#66 ✅ (backend-feature--SuggestCharacters) fix register
  backend/api/app.py
Labels: scope:backend

#74 🔒(Backend-fixes)
  .gitignore
  README.md
  backend/api/__pycache__/authentication.cpython-39.pyc
  backend/api/__pycache__/image.cpython-39.pyc
  backend/api/app.py
  backend/api/authentication.py
  backend/api/image.py
  backend/database/__pycache__/database.cpython-39.pyc
  backend/requirements.txt
  src/app/sign-up/sign-up.page.ts
Labels: scope:backend, scope:frontend

#81 ⚡(Backend featue upload imagefirebase)
  .gitignore
  backend/api/__pycache__/authentication.cpython-39.pyc
  backend/api/__pycache__/image.cpython-39.pyc
  backend/api/app.py
  backend/api/authentication.py
  backend/api/image.py
  backend/requirements.txt
  src/app/home/home.page.ts
Labels: scope:backend, layer:api, layer:service

#85 💄 (Frontend feature upload image) added guest user functionality
  src/app/app-routing.module.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/login/login.page.html
  src/app/login/login.page.scss
  src/app/login/login.page.ts
Labels: scope:frontend, scope:ui
