Repository COS301-SE-2022/Japanese-Writing-Evaluator, pull requests merged in 2022-10, with the labels that each got.

#246 🐛 (backend-architecture-fixes) make backend fail safely when communicating with services
  backend/api/app.py
  backend/services/authentication/authentication.py
  backend/services/detect/detect.py
  backend/services/hiragana/hiragana.py
  backend/services/image/image.py
  backend/services/imageDB/imageDB.py
  backend/services/kanji/kanji.py
  backend/services/katakana/katakana.py
  backend/services/send_email/send_email.py
Labels: scope:backend, layer:api, layer:service, fix, scope:object-detection, layer:object-detection

#247 ✨ (backend-feature-delete) Added user deletion
  backend/api/app.py
  backend/services/authentication/authentication.py
  backend/services/image/image.py
  backend/services/imageDB/imageDB.py
Labels: enhancement, scope:backend, layer:api, layer:service

#251 🔧 (Frontend trackpad) Added deployed api
  ios/App/App/capacitor.config.json
  src/app/services/appService/app-service.service.ts
  src/app/services/objectDetection/object-detection.service.ts
Labels: scope:frontend, scope:ui

#254 ✨Merging develop into deployment
  README.md
Labels: scope:frontend

#256 ✨updates in trackpad into develop
  src/app/drawing-pad/drawing-pad.page.html
  src/app/home/pop-over-upload/pop-over-upload.page.ts
Labels: bug, scope:frontend

#258 🐛 (backend-feature-email) email
  backend/api/Dockerfile
  backend/api/app.py
  backend/services/authentication/authentication.py
  backend/services/detect/detect.py
  backend/services/hiragana/hiragana.py
  backend/services/image/image.py
  backend/services/imageDB/imageDB.py
  backend/services/kanji/kanji.py
  backend/services/katakana/katakana.py
  backend/services/send_email/send_email.py
Labels: enhancement, scope:backend, layer:api

#260 ✨ added background to image for trackpad
  src/app/drawing-pad/drawing-pad.page.ts
Labels: scope:frontend, fix

#261 ✨ Removed back button
  src/app/forgot-password-email/forgot-password-email.page.html
  src/app/sign-up/sign-up.page.html
Labels: scope:frontend

#262 ✨ Update deployment from develop
  README.md
  src/app/drawing-pad/drawing-pad.page.ts
  src/app/forgot-password-email/forgot-password-email.page.html
  src/app/sign-up/sign-up.page.html
Labels: enhancement, scope:frontend
